### ISSUE TITLE
测试中断后重新调起App，bundleID判断失败

### ISSUE THREAD

**Issue by sydowma** [hujiachun/iosMonkey#1]
随手拿微信测试了一下，到30多步的时候崩溃了

```shell
Response content:{"sessionId":"1eef6943-0a51-422d-9d9f-976cc8f7715e","status":10,"value":{"message":"An element command failed because the referenced element is no longer attached to the DOM."}}
An element command failed because the referenced element is no longer attached to the DOM.
请确认参数配置,需要帮助请输入 java -jar iosMonkey.jar -h
ERROR信息java.lang.Exception: An element command failed because the referenced element is no longer attached to the DOM.
==当前启动的APP bundleid是<(null)>,非测试APP，重新呼起测试APP====
==当前启动的APP bundleid是<com.apple.springboard>,非测试APP，重新呼起测试APP====
==当前启动的APP bundleid是<com.tencent.xin>,非测试APP，重新呼起测试APP====
==当前启动的APP bundleid是<(null)>,非测试APP，重新呼起测试APP====
==当前启动的APP bundleid是<com.apple.springboard>,非测试APP，重新呼起测试APP====
```

```shell
>> proxy.js:84:20 [master] pid:53474 Got response with status 200: {"value":"Application is not running, possibly crashed","sessionId":"temp","status":10}
>> responseHandler.js:54:12 [master] pid:53474 Send Error Respone to Client: StaleElementReference: An element command failed because the referenced element is no longer attached to the DOM.
>> responseHandler.js:60:14 [master] pid:53474 StaleElementReference: An element command failed because the referenced element is no longer attached to the DOM.
    at actionDelegate.call.then.result (/usr/local/lib/node_modules/.macaca-ios_npminstall/node_modules/.1.0.59@macaca-ios/lib/actions.js:121:15)
    at process._tickCallback (internal/process/next_tick.js:103:7)
>> responseHandler.js:76:14 [master] pid:53474 Send Bad HTTP Respone to Client: {"sessionId":"1eef6943-0a51-422d-9d9f-976cc8f7715e","status":10,"value":{"message":"An element command failed because the referenced element is no longer attached to the DOM."}}

```

**Comment by hujiachun** [comment]
你要拿debug包测试才行
